package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"enginedj5multitool/db"

	_ "modernc.org/sqlite"
)

// TrackRecord is a row of the Track table as returned by ListTracks
// (generated by sqlc).
type TrackRecord = db.ListTracksRow

// Library wraps an Engine DJ m.db database.
type Library struct {
	DB  *sql.DB
	Dir string // directory containing the database

	MusicRoot     string // optional root used to resolve relative track paths
	EngineLibrary string // Engine Library folder (e.g. ~/Music/Engine Library)

	q *db.Queries
}

// OpenLibrary opens the database. Read-only when readOnly is true.
func OpenLibrary(path string, readOnly bool) (*Library, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		abs = path
	}
	var dsn string
	if readOnly {
		dsn = "file:" + abs + "?mode=ro&immutable=1"
	} else {
		dsn = "file:" + abs + "?mode=rw"
	}
	sqlDB, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, err
	}
	return &Library{DB: sqlDB, Dir: filepath.Dir(abs), q: db.New(sqlDB)}, nil
}

func (l *Library) Close() error {
	return l.DB.Close()
}

// Tracks returns all tracks matching the filter (substring on title, artist,
// album, filename). Empty filter returns everything.
func (l *Library) Tracks(filter string) ([]TrackRecord, error) {
	return l.q.ListTracks(context.Background(), strings.TrimSpace(filter))
}

// LoadDetail loads and parses the performance data (cues, loops, sample rate)
// of a track.
func (l *Library) LoadDetail(rec TrackRecord) (*TrackDetail, error) {
	row, err := l.q.GetPerformanceData(context.Background(), rec.ID)
	if err != nil {
		return nil, err
	}
	return parseTrackDetail(row.TrackData, row.QuickCues, row.Loops, row.ActiveOnLoadLoops)
}

// FixResult is the computed fix for one track, ready to inspect (dry run) or
// write.
type FixResult struct {
	ID      int64
	Compute *FixComputeResult
	detail  *TrackDetail

	qc    []byte
	loops []byte
}

// Write applies the computed fix to the database.
func (r *FixResult) Write(lib *Library) error {
	if r.Compute == nil || (!r.Compute.QCChanged && !r.Compute.LPChanged) {
		return nil
	}
	if r.qc == nil && r.loops == nil {
		r.qc, r.loops = r.Compute.Serialize(r.detail)
	}
	ctx := context.Background()
	switch {
	case r.Compute.QCChanged && r.Compute.LPChanged:
		return lib.q.UpdateQuickCuesAndLoops(ctx, db.UpdateQuickCuesAndLoopsParams{
			QuickCues:         r.qc,
			Loops:             r.loops,
			ActiveOnLoadLoops: r.Compute.Active,
			TrackID:           r.ID,
		})
	case r.Compute.QCChanged:
		return lib.q.UpdateQuickCues(ctx, db.UpdateQuickCuesParams{
			QuickCues: r.qc,
			TrackID:   r.ID,
		})
	default:
		return lib.q.UpdateLoops(ctx, db.UpdateLoopsParams{
			Loops:             r.loops,
			ActiveOnLoadLoops: r.Compute.Active,
			TrackID:           r.ID,
		})
	}
}

// FixTrack computes the cue/loop fix for a track. Returns nil when the track
// is already clean. When dryRun is false the caller must invoke res.Write(lib)
// to persist the changes.
func (l *Library) FixTrack(rec TrackRecord, dryRun bool) (*FixResult, error) {
	d, err := l.LoadDetail(rec)
	if err != nil {
		return nil, err
	}
	compute := ComputeFix(d)
	if !compute.QCChanged && !compute.LPChanged {
		return nil, nil
	}
	res := &FixResult{ID: rec.ID, Compute: compute, detail: d}
	if !dryRun {
		res.qc, res.loops = compute.Serialize(d)
		if err := res.Write(l); err != nil {
			return nil, err
		}
	}
	return res, nil
}

// ResolveMedia turns the (often relative) path stored in the Track table into
// a usable filesystem path using the library's configured roots.
func (l *Library) ResolveMedia(relPath string) string {
	return ResolveMediaPath(l.Dir, l.MusicRoot, l.EngineLibrary, relPath)
}

// macVolumeAlias is the macOS default boot-volume alias: the system disk is
// mounted at "/" and also exposed under /Volumes/<name>.
const macVolumeAlias = "/Volumes/Macintosh HD"

// canonicalPath maps macOS default-mountpoint aliases to the real path:
// /Volumes/Macintosh HD/Users/... == /Users/...
func canonicalPath(p string) string {
	if rest, ok := strings.CutPrefix(p, macVolumeAlias+"/"); ok {
		return "/" + rest
	}
	return p
}

// ResolveMediaPath turns the (often relative) path stored in the Track table
// into a usable filesystem path. Engine DJ databases frequently store paths
// with "../" chains relative to a volume root that no longer matches the DB
// location, so several candidates are tried: the music root, the Engine
// Library folder (e.g. /Users/me/Music/Engine Library), the DB directory,
// a root-anchored form of the trimmed path, and the same path with the
// default macOS volume alias (/Volumes/Macintosh HD) mapped to "/".
// Returned paths are canonical (volume aliases resolved to the real path).
func ResolveMediaPath(dbDir, musicRoot, engineLib, relPath string) string {
	if relPath == "" {
		return ""
	}
	if filepath.IsAbs(relPath) {
		return canonicalPath(relPath)
	}
	// Normalize: strip "./" prefixes; keep the ".." chains — they climb out
	// of the Engine Library folder by design.
	norm := filepath.ToSlash(relPath)
	for strings.HasPrefix(norm, "./") {
		norm = norm[2:]
	}
	trimmed := norm
	for strings.HasPrefix(trimmed, "../") {
		trimmed = trimmed[3:]
	}

	// The Engine Library folder is the base for the stored path (the ".."
	// chains resolve against it); the DB directory is only used as the base
	// when no Engine Library folder is configured.
	libRoot := engineLib
	if libRoot == "" {
		libRoot = dbDir
	}

	var candidates []string
	if libRoot != "" {
		candidates = append(candidates, filepath.Join(libRoot, norm))
	}
	if musicRoot != "" {
		candidates = append(candidates, filepath.Join(musicRoot, trimmed))
	}
	// "/Volumes/Macintosh HD" is the default (/) mountpoint, so strip it:
	// Volumes/Macintosh HD/Users/prune/Music/x.mp3 → /Users/prune/Music/x.mp3
	if rest, ok := strings.CutPrefix(trimmed, strings.TrimPrefix(macVolumeAlias, "/")+"/"); ok {
		candidates = append(candidates, "/"+rest)
	}
	candidates = append(candidates, string(filepath.Separator)+trimmed)

	for _, c := range candidates {
		c = canonicalPath(c)
		if st, err := os.Stat(c); err == nil && !st.IsDir() {
			return c
		}
	}
	// Nothing found: return the most plausible candidate for error reporting.
	return canonicalPath(filepath.Join(libRoot, norm))
}

// UpdateTrackMetadata syncs edited media tags back into the Track table so the
// Engine DJ library matches the file. An unparsable year is stored as 0
// ("no year").
func (l *Library) UpdateTrackMetadata(id int64, t MediaTags) error {
	year, _ := parseYear(t.Year)
	return l.q.UpdateTrackMetadata(context.Background(), db.UpdateTrackMetadataParams{
		Title:    t.Title,
		Artist:   t.Artist,
		Album:    t.Album,
		Genre:    t.Genre,
		Comment:  t.Comment,
		Composer: t.Composer,
		Year:     year,
		ID:       id,
	})
}

// SetTrackRating writes a track's rating (0..100, steps of 20). The DB's own
// trigger bumps Track.lastEditTime so Engine DJ picks up the change.
func (l *Library) SetTrackRating(id int64, rating int64) error {
	if rating < 0 {
		rating = 0
	}
	if rating > 100 {
		rating = 100
	}
	return l.q.SetTrackRating(context.Background(), db.SetTrackRatingParams{
		Rating: rating,
		ID:     id,
	})
}

// SetTrackPath points a track at a new audio file location (relink).
func (l *Library) SetTrackPath(id int64, path string) error {
	return l.q.UpdateTrackPath(context.Background(), db.UpdateTrackPathParams{
		Path: path,
		ID:   id,
	})
}

// DeleteTrack removes a track and its performance data from the library
// (used by the Relink tool for tracks whose audio file is gone for good).
func (l *Library) DeleteTrack(id int64) error {
	ctx := context.Background()
	if err := l.q.DeletePerformanceData(ctx, id); err != nil {
		return err
	}
	return l.q.DeleteTrack(ctx, id)
}

func parseYear(s string) (int64, bool) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, false
	}
	var y int64
	if _, err := fmt.Sscanf(s, "%d", &y); err != nil || y < 0 || y > 3000 {
		return 0, false
	}
	return y, true
}
