// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Performancedatum struct {
	Trackid              int64
	Trackdata            []byte
	Overviewwaveformdata []byte
	Beatdata             []byte
	Quickcues            []byte
	Loops                []byte
	Thirdpartysourceid   sql.NullInt64
	Activeonloadloops    int64
}

type Track struct {
	ID                                   int64
	Playorder                            int64
	Length                               int64
	Bpm                                  int64
	Year                                 int64
	Path                                 string
	Filename                             string
	Bitrate                              sql.NullInt64
	Bpmanalyzed                          float64
	Albumartid                           sql.NullInt64
	Filebytes                            sql.NullInt64
	Title                                string
	Artist                               string
	Album                                string
	Genre                                string
	Comment                              string
	Label                                sql.NullString
	Composer                             string
	Remixer                              sql.NullString
	Key                                  int64
	Rating                               int64
	Albumart                             sql.NullString
	Timelastplayed                       sql.NullTime
	Isplayed                             sql.NullBool
	Filetype                             string
	Isanalyzed                           sql.NullBool
	Datecreated                          sql.NullTime
	Dateadded                            sql.NullTime
	Isavailable                          sql.NullBool
	Ismetadataofpackedtrackchanged       sql.NullBool
	Isperfomancedataofpackedtrackchanged sql.NullBool
	Playedindicator                      sql.NullInt64
	Ismetadataimported                   sql.NullBool
	Pdbimportkey                         sql.NullInt64
	Streamingsource                      sql.NullString
	Uri                                  sql.NullString
	Isbeatgridlocked                     sql.NullBool
	Origindatabaseuuid                   sql.NullString
	Origintrackid                        sql.NullInt64
	Streamingflags                       sql.NullInt64
	Explicitlyrics                       sql.NullBool
	Lastedittime                         sql.NullTime
	Albumartsourcehash                   interface{}
}
