// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const deletePerformanceData = `-- name: DeletePerformanceData :exec
DELETE FROM PerformanceData WHERE trackId = ?1
`

func (q *Queries) DeletePerformanceData(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePerformanceData, id)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM Track WHERE id = ?1
`

func (q *Queries) DeleteTrack(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrack, id)
	return err
}

const getPerformanceData = `-- name: GetPerformanceData :one
SELECT
	trackData AS track_data,
	quickCues AS quick_cues,
	loops AS loops,
	COALESCE(activeOnLoadLoops, 0) AS active_on_load_loops
FROM PerformanceData
WHERE trackId = ?1
`

type GetPerformanceDataRow struct {
	TrackData         []byte
	QuickCues         []byte
	Loops             []byte
	ActiveOnLoadLoops int64
}

func (q *Queries) GetPerformanceData(ctx context.Context, trackID int64) (GetPerformanceDataRow, error) {
	row := q.db.QueryRowContext(ctx, getPerformanceData, trackID)
	var i GetPerformanceDataRow
	err := row.Scan(
		&i.TrackData,
		&i.QuickCues,
		&i.Loops,
		&i.ActiveOnLoadLoops,
	)
	return i, err
}

const listTracks = `-- name: ListTracks :many

SELECT
	id,
	COALESCE(title, '') AS title,
	COALESCE(artist, '') AS artist,
	COALESCE(album, '') AS album,
	COALESCE(filename, '') AS filename,
	COALESCE(path, '') AS path,
	COALESCE(fileType, '') AS file_type,
	CAST(COALESCE(bpmAnalyzed, 0) AS REAL) AS bpm_analyzed,
	COALESCE(bpm, 0) AS bpm_file,
	COALESCE(year, 0) AS year,
	COALESCE(playOrder, 0) AS play_order,
	COALESCE(rating, 0) AS rating,
	COALESCE("key", -1) AS "key",
	COALESCE(fileBytes, 0) AS file_bytes,
	COALESCE(length, 0) AS length
FROM Track
WHERE (
	?1 = ''
	OR title LIKE '%' || ?1 || '%'
	OR artist LIKE '%' || ?1 || '%'
	OR album LIKE '%' || ?1 || '%'
	OR filename LIKE '%' || ?1 || '%'
	OR comment LIKE '%' || ?1 || '%'
)
ORDER BY artist, title
`

type ListTracksRow struct {
	ID        int64
	Title     string
	Artist    string
	Album     string
	Filename  string
	Path      string
	FileType  string
	BPM       float64
	BPMFile   int64
	Year      int64
	PlayOrder int64
	Rating    int64
	Key       int64
	FileBytes int64
	Length    int64
}

// Queries used by the library layer (library.go).
func (q *Queries) ListTracks(ctx context.Context, filter interface{}) ([]ListTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracks, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Filename,
			&i.Path,
			&i.FileType,
			&i.BPM,
			&i.BPMFile,
			&i.Year,
			&i.PlayOrder,
			&i.Rating,
			&i.Key,
			&i.FileBytes,
			&i.Length,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrackRating = `-- name: SetTrackRating :exec
UPDATE Track SET rating = ?1 WHERE id = ?2
`

type SetTrackRatingParams struct {
	Rating int64
	ID     int64
}

func (q *Queries) SetTrackRating(ctx context.Context, arg SetTrackRatingParams) error {
	_, err := q.db.ExecContext(ctx, setTrackRating, arg.Rating, arg.ID)
	return err
}

const updateLoops = `-- name: UpdateLoops :exec
UPDATE PerformanceData
SET loops = ?1, activeOnLoadLoops = ?2
WHERE trackId = ?3
`

type UpdateLoopsParams struct {
	Loops             []byte
	ActiveOnLoadLoops int64
	TrackID           int64
}

func (q *Queries) UpdateLoops(ctx context.Context, arg UpdateLoopsParams) error {
	_, err := q.db.ExecContext(ctx, updateLoops, arg.Loops, arg.ActiveOnLoadLoops, arg.TrackID)
	return err
}

const updateQuickCues = `-- name: UpdateQuickCues :exec
UPDATE PerformanceData
SET quickCues = ?1
WHERE trackId = ?2
`

type UpdateQuickCuesParams struct {
	QuickCues []byte
	TrackID   int64
}

func (q *Queries) UpdateQuickCues(ctx context.Context, arg UpdateQuickCuesParams) error {
	_, err := q.db.ExecContext(ctx, updateQuickCues, arg.QuickCues, arg.TrackID)
	return err
}

const updateQuickCuesAndLoops = `-- name: UpdateQuickCuesAndLoops :exec
UPDATE PerformanceData
SET quickCues = ?1,
    loops = ?2,
    activeOnLoadLoops = ?3
WHERE trackId = ?4
`

type UpdateQuickCuesAndLoopsParams struct {
	QuickCues         []byte
	Loops             []byte
	ActiveOnLoadLoops int64
	TrackID           int64
}

func (q *Queries) UpdateQuickCuesAndLoops(ctx context.Context, arg UpdateQuickCuesAndLoopsParams) error {
	_, err := q.db.ExecContext(ctx, updateQuickCuesAndLoops,
		arg.QuickCues,
		arg.Loops,
		arg.ActiveOnLoadLoops,
		arg.TrackID,
	)
	return err
}

const updateTrackMetadata = `-- name: UpdateTrackMetadata :exec
UPDATE Track
SET title = ?1, artist = ?2, album = ?3,
    genre = ?4, comment = ?5, composer = ?6,
    year = ?7
WHERE id = ?8
`

type UpdateTrackMetadataParams struct {
	Title    string
	Artist   string
	Album    string
	Genre    string
	Comment  string
	Composer string
	Year     int64
	ID       int64
}

func (q *Queries) UpdateTrackMetadata(ctx context.Context, arg UpdateTrackMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateTrackMetadata,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Genre,
		arg.Comment,
		arg.Composer,
		arg.Year,
		arg.ID,
	)
	return err
}

const updateTrackPath = `-- name: UpdateTrackPath :exec
UPDATE Track SET path = ?1 WHERE id = ?2
`

type UpdateTrackPathParams struct {
	Path string
	ID   int64
}

func (q *Queries) UpdateTrackPath(ctx context.Context, arg UpdateTrackPathParams) error {
	_, err := q.db.ExecContext(ctx, updateTrackPath, arg.Path, arg.ID)
	return err
}
